### ISSUE TITLE
Intermittent failure of fallback_ru_to_en unit test

### ISSUE THREAD

**Issue by kellpossible** [kellpossible/cargo-i18n#48]
Sometimes when running the unit tests in `i18n-embed/tests/loader.rs` I get a failure:

```
> Executing task: cargo test --package i18n-embed --test loader --all-features -- gettext --nocapture <

    Finished test [unoptimized + debuginfo] target(s) in 0.07s
     Running target/debug/deps/loader-a834f4ae71a337bd

running 2 tests
test gettext::only_en ... ok
thread 'gettext::fallback_ru_to_en' panicked at 'assertion failed: `(left == right)`

Diff < left / right > :
<"только ру"
>"only ru"

', i18n-embed/tests/loader.rs:135:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/fe982319aa0aa5bbfc2795791a753832292bd2ba/library/std/src/panicking.rs:493:5
   1: std::panicking::begin_panic_fmt
             at /rustc/fe982319aa0aa5bbfc2795791a753832292bd2ba/library/std/src/panicking.rs:435:5
   2: loader::gettext::fallback_ru_to_en
             at ./tests/loader.rs:135:9
   3: loader::gettext::fallback_ru_to_en::{{closure}}
             at ./tests/loader.rs:127:5
   4: core::ops::function::FnOnce::call_once
             at /home/luke/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:227:5
   5: core::ops::function::FnOnce::call_once
             at /rustc/fe982319aa0aa5bbfc2795791a753832292bd2ba/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
test gettext::fallback_ru_to_en ... FAILED

failures:

failures:
    gettext::fallback_ru_to_en
```

**Comment by bikeshedder** [comment]
`cargo test` runs the tests in threads. The `gettext` tests however are not thread safe as they use the shared `LOADER` which is initialized inside the `lazy_static` block. It is just a matter of (bad) luck to end up with both tests executing concurrently. `GetTextLanguageLoader::load_langauges` does set the `current_language` which causes the tests to fail in a random fashion.

`gettext::only_en` and `gettext::fallback_ru_to_en` are easy to fix by moving the `loader` into the test functions. The code base is full of `lazy_static` though and there are more tests that fail randomly for the same reason.

The easiest way to fix this is running the tests single threaded:

```sh
cargo test --workspace --all-features -- --test-threads 1
```

https://doc.rust-lang.org/book/ch11-02-running-tests.html#running-tests-in-parallel-or-consecutively

A better way would be to make fluent thread safe by putting the current language in a thread local object instead. With that change it would no longer be possible to switch the current language for the entire running program though. That's why I think that choice should be made by the user instead. I was thinking about a `CurrentLanguage` trait which could be implemented by `ApplicationCurrentLanguage` and `ThreadCurrentLanguage` allowing for swapping out the current language implementation at loader creation time.

I guess the easiest fix (for now) is to add the `--test-threads 1` to the CI pipeline and call it the day.

**Comment by bikeshedder** [comment]
Just one important note: While using a thread local object might fix it for sync applications with multiple threads it still will break async code. That's why runtimes like tokio have their own implementation of a "task-local": https://docs.rs/tokio/1.16.1/tokio/task/struct.LocalKey.html

**Comment by kellpossible** [comment]
@bikeshedder thanks for the contribution and MR! Perhaps we could just instead create a new `GettextLanguageLoader` per test, in the same style as the fluent tests?

**Comment by bikeshedder** [comment]
Sure. I just added that change to the PR. It doesn't fix the other tests which are prone to this issue though. If you run the tests often enough you can get an error out of the tests for the `FluentLoader` which uses global state (`lazy_static`) internally. For those to work properly the `--test-threads 1` is still required.

**Comment by kellpossible** [comment]
Actually I just triggered the error again,  gettext uses a global static variable for its state under the hood.

**Comment by bikeshedder** [comment]
Have you tried running the tests with `--test-threads 1`? Unless the tests don't properly reset everything the errors should go away.

**Comment by kellpossible** [comment]
>  I was thinking about a CurrentLanguage trait which could be implemented by ApplicationCurrentLanguage and ThreadCurrentLanguage allowing for swapping out the current language implementation at loader creation time.

I like this suggestion, do you think it's worth creating a new issue for it?

**Comment by bikeshedder** [comment]
@kellpossible I just opened #82. I'm currently working on #59. I'm on Discord and tried contacting you. If you're open to some discussion I'd love to talk to you about some implementation details that I noticed while working on the code base.
